#!/bin/sh

DIREC_TTMM=${PWD##*/}
if (tmux has-session -t "${PWD##*/}" 2> /dev/null); then
        echo "Session  ${PWD##*/} exists."
        if [ -z $TMUX ]; then
            echo "You are in tmux session"
            echo "Attach to session ${PWD##*/}"
            tmux attach-session -t "${PWD##*/}"
        else
            echo "Switch to session $DIREC_TTMM"
            tmux switch -t "$DIREC_TTMM"
        fi
    else
#       -z the length of string is zero        
        if [ -z $TMUX ]; then
            echo "Starting session ${PWD##*/}"
            tmux new -s "${PWD##*/}" -d
            tmux new-window -n "${PWD##*/}:1"
            tmux new-window -n "${PWD##*/}:2"
            tmux new-window -n "${PWD##*/}:3"
            tmux new-window -n "${PWD##*/}:4"
            tmux new-window -n "${PWD##*/}:5"
            tmux new-window -n "${PWD##*/}:6"
            tmux new-window -n "${PWD##*/}:7"

            tmux send-keys -t "${PWD##*/}:0" 'htop' C-m
            tmux send-keys -t "${PWD##*/}:1" 'mc' C-m
            tmux send-keys -t "${PWD##*/}:2" 'vim' C-m
            tmux send-keys -t "${PWD##*/}:3" 'source virt/2/bin/activate;python manage.py runserver 0.0.0.0:8000' C-m
            tmux attach-session -t "${PWD##*/}"
        else
            echo "You are in tmux session"
            echo "Create session - $DIREC_TTMM"
            tmux new -s "$DIREC_TTMM" -d
            tmux new-window -n "$DIREC_TTMM" -t "$DIREC_TTMM:1"
            tmux new-window -n "$DIREC_TTMM" -t "$DIREC_TTMM:2"
            tmux new-window -n "$DIREC_TTMM" -t "$DIREC_TTMM:3"
            tmux new-window -n "$DIREC_TTMM" -t "$DIREC_TTMM:4"
            tmux new-window -n "$DIREC_TTMM" -t "$DIREC_TTMM:5"
            tmux new-window -n "$DIREC_TTMM" -t "$DIREC_TTMM:6"
            tmux new-window -n "$DIREC_TTMM" -t "$DIREC_TTMM:7"


            tmux send-keys -t "$DIREC_TTMM:0" 'htop' C-m
            tmux send-keys -t "$DIREC_TTMM:1" 'mc' C-m
            tmux send-keys -t "$DIREC_TTMM:2" 'vim' C-m
            tmux send-keys -t "$DIREC_TTMM:3" 'source virt/2/bin/activate;python manage.py runserver 0.0.0.0:8000' C-m

            tmux switch -t "$DIREC_TTMM:3"
        fi
fi

    # if (tmux has-session -t "${PWD##*/}" 2> /dev/null); then
    #     echo "Session  ${PWD##*/} exists."
    # else
    #         tmux new -s "${PWD##*/}" -d
    #         tmux new-window -n "${PWD##*/}:1"
    #         tmux new-window -n "${PWD##*/}:2"
    #         tmux new-window -n "${PWD##*/}:3"
    #         tmux new-window -n "${PWD##*/}:4"
    #         tmux new-window -n "${PWD##*/}:5"
    #         tmux new-window -n "${PWD##*/}:6"
    #         tmux new-window -n "${PWD##*/}:7"
    #
    #         tmux send-keys -t "${PWD##*/}:0" 'htop' C-m
    #         tmux send-keys -t "${PWD##*/}:1" 'mc' C-m
    #         tmux send-keys -t "${PWD##*/}:2" 'vim' C-m
    #         tmux send-keys -t "${PWD##*/}:3" 'source virt/2/bin/activate;python manage.py runserver 0.0.0.0:8000' C-m
    #
    #         tmux select-window -t "${PWD##*/}:3" 
    # fi
    # tmux attach-session -t "${PWD##*/}" 



